// Mapping from advancement ID suffix to display name
// Extracted from Minecraft 26.2 client JAR (assets/minecraft/lang/en_us.json)
const ADVANCEMENT_NAMES: Record<string, string> = {
  // Story
  'story/root': 'Minecraft',
  'story/mine_stone': 'Stone Age',
  'story/upgrade_tools': 'Getting an Upgrade',
  'story/smelt_iron': 'Acquire Hardware',
  'story/obtain_armor': 'Suit Up',
  'story/iron_tools': "Isn't It Iron Pick",
  'story/mine_diamond': 'Diamonds!',
  'story/form_obsidian': 'Ice Bucket Challenge',
  'story/enter_the_nether': 'We Need to Go Deeper',
  'story/lava_bucket': 'Hot Stuff',
  'story/shiny_gear': 'Cover Me with Diamonds',
  'story/follow_ender_eye': 'Eye Spy',
  'story/enter_the_end': 'The End?',
  'story/enchant_item': 'Enchanter',
  'story/deflect_arrow': 'Not Today, Thank You',
  'story/cure_zombie_villager': 'Zombie Doctor',

  // Nether
  'nether/root': 'Nether',
  'nether/return_to_sender': 'Return to Sender',
  'nether/obtain_blaze_rod': 'Into Fire',
  'nether/uneasy_alliance': 'Uneasy Alliance',
  'nether/find_fortress': 'A Terrible Fortress',
  'nether/get_wither_skull': 'Spooky Scary Skeleton',
  'nether/summon_wither': 'Withering Heights',
  'nether/brew_potion': 'Local Brewery',
  'nether/all_potions': 'A Furious Cocktail',
  'nether/all_effects': 'How Did We Get Here?',
  'nether/create_beacon': 'Bring Home the Beacon',
  'nether/create_full_beacon': 'Beaconator',
  'nether/explore_nether': 'Hot Tourist Destinations',
  'nether/fast_travel': 'Subspace Bubble',
  'nether/ride_strider': 'This Boat Has Legs',
  'nether/ride_strider_in_overworld_lava': 'Feels Like Home',
  'nether/find_bastion': 'Those Were the Days',
  'nether/loot_bastion': 'War Pigs',
  'nether/distract_piglin': 'Oh Shiny',
  'nether/obtain_ancient_debris': 'Hidden in the Depths',
  'nether/netherite_armor': 'Cover Me in Debris',
  'nether/obtain_crying_obsidian': 'Who is Cutting Onions?',
  'nether/charge_respawn_anchor': 'Not Quite "Nine" Lives',
  'nether/use_lodestone': 'Country Lode, Take Me Home',

  // End
  'end/root': 'The End',
  'end/kill_dragon': 'Free the End',
  'end/dragon_egg': 'The Next Generation',
  'end/respawn_dragon': 'The End... Again...',
  'end/dragon_breath': 'You Need a Mint',
  'end/find_end_city': 'The City at the End of the Game',
  'end/elytra': "Sky's the Limit",
  'end/levitate': 'Great View From Up Here',
  'end/enter_end_gateway': 'Remote Getaway',

  // Adventure
  'adventure/root': 'Adventure',
  'adventure/kill_a_mob': 'Monster Hunter',
  'adventure/kill_all_mobs': 'Monsters Hunted',
  'adventure/trade': 'What a Deal!',
  'adventure/honey_block_slide': 'Sticky Situation',
  'adventure/dolphins_play': 'Is It a Bird?',
  'adventure/hero_of_the_village': 'Hero of the Village',
  'adventure/sleep_in_bed': 'Sweet Dreams',
  'adventure/sniper_duel': 'Sniper Duel',
  'adventure/voluntary_exile': 'Voluntary Exile',
  'adventure/adventuring_time': 'Adventuring Time',
  'adventure/spyglass_at_parrot': 'Is It a Bird?',
  'adventure/spyglass_at_ghast': 'Is It a Balloon?',
  'adventure/spyglass_at_dragon': 'Is It a Plane?',
  'adventure/very_very_frightening': 'Very Very Frightening',
  'adventure/two_birds_one_arrow': 'Two Birds, One Arrow',
  'adventure/whos_the_pillager_now': "Who's the Pillager Now?",
  'adventure/arbalistic': 'Arbalistic',
  'adventure/totem_of_undying': 'Postmortal',
  'adventure/throw_trident': 'A Throwaway Joke',
  'adventure/ol_betsy': "Ol' Betsy",
  'adventure/shoot_arrow': 'Take Aim',
  'adventure/bullseye': 'Bullseye',
  'adventure/dangerous_arena': 'Sneak 100',
  'adventure/avoid_vibration': 'Sneak 100',
  'adventure/fall_from_world_height': 'Caves & Cliffs',
  'adventure/under_lock_and_key': 'Under Lock and Key',
  'adventure/under_lock_and_key': 'Under Lock and Key',
  'adventure/revaulting': 'Revaulting',
  'adventure/use_lodestone': 'Country Lode, Take Me Home',
  'adventure/salvage_sherd': 'Respecting the Remnants',
  'adventure/craft_decorated_pot_using_only_sherds': 'Careful Restoration',
  'adventure/trim_with_any_armor_pattern': 'Crafting a New Look',
  'adventure/trim_with_all_exclusive_armor_patterns': 'Smithing with Style',
  'adventure/summon_iron_golem': 'Hired Help',
  'adventure/trade_at_world_height': 'Star Trader',
  'adventure/kill_mob_near_sculk_catalyst': 'It Spreads',
  'adventure/lighten_up': 'Lighten Up',
  'adventure/play_jukebox_in_meadows': 'Sound of Music',
  'adventure/read_power_from_chiseled_bookshelf': 'The Power of Books',
  'adventure/lightning_rod_with_villager_no_fire': 'Surge Protector',
  'adventure/blowback': 'Blowback',
  'adventure/heart_transplanter': 'Heart Transplanter',
  'adventure/brush_armadillo': "Isn't It Scute?",
  'adventure/spear_many_mobs': 'Mob Kabob',
  'adventure/overoverkill': 'Over-Overkill',
  'adventure/crafters_crafting_crafters': 'Crafters Crafting Crafters',
  'adventure/minecraft_trials_edition': 'Minecraft: Trial(s) Edition',
  'adventure/walk_on_powder_snow_with_leather_boots': 'Light as a Rabbit',
  'adventure/who_needs_rockets': 'Who Needs Rockets?',

  // Husbandry
  'husbandry/root': 'Husbandry',
  'husbandry/plant_seed': 'A Seedy Place',
  'husbandry/breed_an_animal': 'The Parrots and the Bats',
  'husbandry/breed_all_animals': 'Two by Two',
  'husbandry/tame_an_animal': 'Best Friends Forever',
  'husbandry/fishy_business': 'Fishy Business',
  'husbandry/slaughter_fish': 'Tactical Fishing',
  'husbandry/tactical_fishing': 'Tactical Fishing',
  'husbandry/silk_touch_nest': 'Total Beelocation',
  'husbandry/safely_harvest_honey': 'Bee Our Guest',
  'husbandry/balanced_diet': 'A Balanced Diet',
  'husbandry/ride_a_boat_with_a_goat': 'Whatever Floats Your Goat!',
  'husbandry/make_a_sign_glow': 'Glow and Behold!',
  'husbandry/froglights': 'With Our Powers Combined!',
  'husbandry/tadpole_in_a_bucket': 'Bukkit Bukkit',
  'husbandry/complete_catalogue': 'A Complete Catalogue',
  'husbandry/axolotl_in_a_bucket': 'The Cutest Predator',
  'husbandry/kill_axolotl_target': 'The Healing Power of Friendship!',
  'husbandry/allay_deliver_item_to_player': "You've Got a Friend in Me",
  'husbandry/allay_deliver_cake_to_note_block': 'Birthday Song',
  'husbandry/leash_all_frog_variants': 'When the Squad Hops into Town',
  'husbandry/netherite_hoe': 'Serious Dedication',
  'husbandry/obtain_sniffer_egg': 'Smells Interesting',
  'husbandry/plant_any_sniffer_seed': 'Planting the Past',
  'husbandry/feed_snifflet': 'Little Sniffs',
  'husbandry/remove_wolf_armor': 'Shear Brilliance',
  'husbandry/repair_wolf_armor': 'Good as New',
  'husbandry/uh_oh': 'Uh Oh',
  'husbandry/wax_on': 'Wax On',
  'husbandry/wax_off': 'Wax Off',
  'husbandry/whole_pack': 'The Whole Pack'
};

/**
 * Convert an advancement ID to its in-game display name.
 * e.g. "minecraft:story/mine_stone" -> "Stone Age"
 */
export function getAdvancementDisplayName(id: string): string {
  const suffix = id.replace('minecraft:', '');
  return ADVANCEMENT_NAMES[suffix] ?? suffix.replace(/_/g, ' ');
}
