// Mapping from Minecraft item/block/entity ID (without minecraft: prefix) to display name
// Extracted from Minecraft 26.2 client JAR (assets/minecraft/lang/en_us.json)
export const ITEM_NAMES: Record<string, string> = {
  acacia_boat: 'Acacia Boat',
  acacia_leaves: 'Acacia Leaves',
  acacia_log: 'Acacia Log',
  acacia_planks: 'Acacia Planks',
  acacia_sapling: 'Acacia Sapling',
  activator_rail: 'Activator Rail',
  air: 'Air',
  amethyst_block: 'Block of Amethyst',
  andesite: 'Andesite',
  anvil: 'Anvil',
  apple: 'Apple',
  arrow: 'Arrow',
  azalea: 'Azalea',
  azure_bluet: 'Azure Bluet',
  baked_potato: 'Baked Potato',
  barrel: 'Barrel',
  bee_nest: 'Bee Nest',
  beetroot: 'Beetroot',
  beetroot_seeds: 'Beetroot Seeds',
  beetroots: 'Beetroots',
  birch_boat: 'Birch Boat',
  birch_leaves: 'Birch Leaves',
  birch_log: 'Birch Log',
  birch_planks: 'Birch Planks',
  birch_sapling: 'Birch Sapling',
  black_bed: 'Black Bed',
  black_dye: 'Black Dye',
  black_wool: 'Black Wool',
  blue_bed: 'Blue Bed',
  blue_dye: 'Blue Dye',
  blue_orchid: 'Blue Orchid',
  blue_wool: 'Blue Wool',
  bone: 'Bone',
  bone_block: 'Bone Block',
  bone_meal: 'Bone Meal',
  book: 'Book',
  bow: 'Bow',
  bread: 'Bread',
  brewing_stand: 'Brewing Stand',
  brick: 'Brick',
  brown_banner: 'Brown Banner',
  brown_wall_banner: 'Brown Wall Banner',
  bucket: 'Bucket',
  budding_amethyst: 'Budding Amethyst',
  bundle: 'Bundle',
  bush: 'Bush',
  calcite: 'Calcite',
  campfire: 'Campfire',
  carrot: 'Carrot',
  carrots: 'Carrots',
  cave_spider: 'Cave Spider',
  cave_vines: 'Cave Vines',
  cave_vines_plant: 'Cave Vines Plant',
  charcoal: 'Charcoal',
  cherry_door: 'Cherry Door',
  cherry_fence: 'Cherry Fence',
  cherry_leaves: 'Cherry Leaves',
  cherry_log: 'Cherry Log',
  cherry_planks: 'Cherry Planks',
  cherry_pressure_plate: 'Cherry Pressure Plate',
  cherry_sapling: 'Cherry Sapling',
  cherry_slab: 'Cherry Slab',
  cherry_stairs: 'Cherry Stairs',
  cherry_trapdoor: 'Cherry Trapdoor',
  chest: 'Chest',
  chest_minecart: 'Minecart with Chest',
  chicken: 'Raw Chicken',
  chiseled_stone_bricks: 'Chiseled Stone Bricks',
  clay: 'Clay',
  clay_ball: 'Clay Ball',
  coal: 'Coal',
  coal_ore: 'Coal Ore',
  coarse_dirt: 'Coarse Dirt',
  cobbled_deepslate: 'Cobbled Deepslate',
  cobbled_deepslate_stairs: 'Cobbled Deepslate Stairs',
  cobbled_deepslate_wall: 'Cobbled Deepslate Wall',
  cobblestone: 'Cobblestone',
  cobblestone_slab: 'Cobblestone Slab',
  cobblestone_stairs: 'Cobblestone Stairs',
  cobblestone_wall: 'Cobblestone Wall',
  cobweb: 'Cobweb',
  compass: 'Compass',
  composter: 'Composter',
  copper_block: 'Block of Copper',
  copper_boots: 'Copper Boots',
  copper_chestplate: 'Copper Chestplate',
  copper_helmet: 'Copper Helmet',
  copper_hoe: 'Copper Hoe',
  copper_horse_armor: 'Copper Horse Armor',
  copper_ingot: 'Copper Ingot',
  copper_leggings: 'Copper Leggings',
  copper_ore: 'Copper Ore',
  copper_pickaxe: 'Copper Pickaxe',
  copper_shovel: 'Copper Shovel',
  copper_sword: 'Copper Sword',
  cornflower: 'Cornflower',
  crafting_table: 'Crafting Table',
  creeper: 'Creeper',
  dandelion: 'Dandelion',
  dark_oak_door: 'Dark Oak Door',
  dark_oak_fence: 'Dark Oak Fence',
  dark_oak_log: 'Dark Oak Log',
  dark_oak_planks: 'Dark Oak Planks',
  dark_oak_slab: 'Dark Oak Slab',
  dead_bush: 'Dead Bush',
  deepslate: 'Deepslate',
  deepslate_coal_ore: 'Deepslate Coal Ore',
  deepslate_copper_ore: 'Deepslate Copper Ore',
  deepslate_diamond_ore: 'Deepslate Diamond Ore',
  deepslate_gold_ore: 'Deepslate Gold Ore',
  deepslate_iron_ore: 'Deepslate Iron Ore',
  deepslate_lapis_ore: 'Deepslate Lapis Lazuli Ore',
  deepslate_redstone_ore: 'Deepslate Redstone Ore',
  diamond: 'Diamond',
  diamond_boots: 'Diamond Boots',
  diamond_chestplate: 'Diamond Chestplate',
  diamond_helmet: 'Diamond Helmet',
  diamond_leggings: 'Diamond Leggings',
  diamond_ore: 'Diamond Ore',
  diamond_pickaxe: 'Diamond Pickaxe',
  diamond_shovel: 'Diamond Shovel',
  diamond_sword: 'Diamond Sword',
  diorite: 'Diorite',
  dirt: 'Dirt',
  dirt_path: 'Dirt Path',
  dried_ghast: 'Dried Ghast',
  dripstone_block: 'Dripstone Block',
  egg: 'Egg',
  emerald: 'Emerald',
  emerald_ore: 'Emerald Ore',
  enchanting_table: 'Enchanting Table',
  ender_pearl: 'Ender Pearl',
  enderman: 'Enderman',
  experience_bottle: "Bottle o' Enchanting",
  farmland: 'Farmland',
  feather: 'Feather',
  fern: 'Fern',
  fire: 'Fire',
  fire_charge: 'Fire Charge',
  firefly_bush: 'Firefly Bush',
  flint: 'Flint',
  flint_and_steel: 'Flint and Steel',
  flower_pot: 'Flower Pot',
  flowering_azalea: 'Flowering Azalea',
  frosted_ice: 'Frosted Ice',
  furnace: 'Furnace',
  glass: 'Glass',
  glass_bottle: 'Glass Bottle',
  glass_pane: 'Glass Pane',
  glow_berries: 'Glow Berries',
  glow_ink_sac: 'Glow Ink Sac',
  glow_lichen: 'Glow Lichen',
  goat_horn: 'Goat Horn',
  gold_block: 'Block of Gold',
  gold_ingot: 'Gold Ingot',
  gold_nugget: 'Gold Nugget',
  golden_apple: 'Golden Apple',
  golden_axe: 'Golden Axe',
  golden_boots: 'Golden Boots',
  golden_leggings: 'Golden Leggings',
  golden_shovel: 'Golden Shovel',
  granite: 'Granite',
  grass_block: 'Grass Block',
  gravel: 'Gravel',
  gray_bed: 'Gray Bed',
  gray_wool: 'Gray Wool',
  gunpowder: 'Gunpowder',
  hay_block: 'Hay Bale',
  ink_sac: 'Ink Sac',
  iron_axe: 'Iron Axe',
  iron_block: 'Block of Iron',
  iron_boots: 'Iron Boots',
  iron_chain: 'Iron Chain',
  iron_chestplate: 'Iron Chestplate',
  iron_golem: 'Iron Golem',
  iron_helmet: 'Iron Helmet',
  iron_hoe: 'Iron Hoe',
  iron_ingot: 'Iron Ingot',
  iron_leggings: 'Iron Leggings',
  iron_nugget: 'Iron Nugget',
  iron_ore: 'Iron Ore',
  iron_pickaxe: 'Iron Pickaxe',
  iron_shovel: 'Iron Shovel',
  iron_spear: 'Iron Spear',
  iron_sword: 'Iron Sword',
  jungle_boat: 'Jungle Boat',
  jungle_leaves: 'Jungle Leaves',
  jungle_log: 'Jungle Log',
  jungle_planks: 'Jungle Planks',
  kelp: 'Kelp',
  kelp_plant: 'Kelp Plant',
  lantern: 'Lantern',
  lapis_lazuli: 'Lapis Lazuli',
  lapis_ore: 'Lapis Lazuli Ore',
  lead: 'Lead',
  leaf_litter: 'Leaf Litter',
  leather: 'Leather',
  leather_chestplate: 'Leather Tunic',
  leather_helmet: 'Leather Cap',
  light_blue_wool: 'Light Blue Wool',
  light_gray_bed: 'Light Gray Bed',
  light_gray_wool: 'Light Gray Wool',
  lilac: 'Lilac',
  lily_of_the_valley: 'Lily of the Valley',
  lily_pad: 'Lily Pad',
  lodestone: 'Lodestone',
  mangrove_leaves: 'Mangrove Leaves',
  mangrove_log: 'Mangrove Log',
  mangrove_propagule: 'Mangrove Propagule',
  mangrove_roots: 'Mangrove Roots',
  melon: 'Melon',
  melon_seeds: 'Melon Seeds',
  melon_slice: 'Melon Slice',
  milk_bucket: 'Milk Bucket',
  moss_block: 'Moss Block',
  moss_carpet: 'Moss Carpet',
  mossy_cobblestone: 'Mossy Cobblestone',
  mud: 'Mud',
  muddy_mangrove_roots: 'Muddy Mangrove Roots',
  mushroom_stem: 'Mushroom Stem',
  mutton: 'Raw Mutton',
  name_tag: 'Name Tag',
  nether_gold_ore: 'Nether Gold Ore',
  nether_quartz_ore: 'Nether Quartz Ore',
  netherrack: 'Netherrack',
  oak_boat: 'Oak Boat',
  oak_door: 'Oak Door',
  oak_fence: 'Oak Fence',
  oak_fence_gate: 'Oak Fence Gate',
  oak_leaves: 'Oak Leaves',
  oak_log: 'Oak Log',
  oak_planks: 'Oak Planks',
  oak_sapling: 'Oak Sapling',
  oak_sign: 'Oak Sign',
  oak_slab: 'Oak Slab',
  oak_stairs: 'Oak Stairs',
  oak_trapdoor: 'Oak Trapdoor',
  obsidian: 'Obsidian',
  ominous_bottle: 'Ominous Bottle',
  orange_terracotta: 'Orange Terracotta',
  oxeye_daisy: 'Oxeye Daisy',
  packed_ice: 'Packed Ice',
  peony: 'Peony',
  pillager: 'Pillager',
  pink_wool: 'Pink Wool',
  podzol: 'Podzol',
  pointed_dripstone: 'Pointed Dripstone',
  poisonous_potato: 'Poisonous Potato',
  polished_deepslate: 'Polished Deepslate',
  poppy: 'Poppy',
  potato: 'Potato',
  potatoes: 'Potatoes',
  powder_snow: 'Powder Snow',
  powered_rail: 'Powered Rail',
  pumpkin: 'Pumpkin',
  pumpkin_pie: 'Pumpkin Pie',
  pumpkin_seeds: 'Pumpkin Seeds',
  quartz: 'Nether Quartz',
  rail: 'Rail',
  raw_copper: 'Raw Copper',
  raw_gold: 'Raw Gold',
  raw_iron: 'Raw Iron',
  red_bed: 'Red Bed',
  red_carpet: 'Red Carpet',
  red_dye: 'Red Dye',
  red_mushroom: 'Red Mushroom',
  red_mushroom_block: 'Red Mushroom Block',
  red_wool: 'Red Wool',
  redstone: 'Redstone Dust',
  redstone_ore: 'Redstone Ore',
  rotten_flesh: 'Rotten Flesh',
  saddle: 'Saddle',
  salmon: 'Raw Salmon',
  sand: 'Sand',
  seagrass: 'Seagrass',
  shears: 'Shears',
  sheep: 'Sheep',
  short_grass: 'Short Grass',
  skeleton: 'Skeleton',
  smooth_basalt: 'Smooth Basalt',
  soul_fire: 'Soul Fire',
  soul_sand: 'Soul Sand',
  soul_soil: 'Soul Soil',
  spawner: 'Monster Spawner',
  spider: 'Spider',
  spider_eye: 'Spider Eye',
  spruce_fence: 'Spruce Fence',
  spruce_leaves: 'Spruce Leaves',
  spruce_log: 'Spruce Log',
  spruce_planks: 'Spruce Planks',
  spruce_sapling: 'Spruce Sapling',
  squid: 'Squid',
  stick: 'Stick',
  stone: 'Stone',
  stone_axe: 'Stone Axe',
  stone_brick_slab: 'Stone Brick Slab',
  stone_brick_stairs: 'Stone Brick Stairs',
  stone_bricks: 'Stone Bricks',
  stone_hoe: 'Stone Hoe',
  stone_pickaxe: 'Stone Pickaxe',
  stone_shovel: 'Stone Shovel',
  stone_spear: 'Stone Spear',
  stone_sword: 'Stone Sword',
  stonecutter: 'Stonecutter',
  string: 'String',
  stripped_oak_log: 'Stripped Oak Log',
  sugar_cane: 'Sugar Cane',
  tall_grass: 'Tall Grass',
  tall_seagrass: 'Tall Seagrass',
  torch: 'Torch',
  trader_llama: 'Trader Llama',
  tropical_fish_bucket: 'Bucket of Tropical Fish',
  tuff: 'Tuff',
  villager: 'Villager',
  vine: 'Vines',
  wall_torch: 'Wall Torch',
  wandering_trader: 'Wandering Trader',
  water_bucket: 'Water Bucket',
  wheat: 'Wheat',
  wheat_seeds: 'Wheat Seeds',
  white_banner: 'White Banner',
  white_bed: 'White Bed',
  white_carpet: 'White Carpet',
  white_terracotta: 'White Terracotta',
  white_wall_banner: 'White Wall Banner',
  white_wool: 'White Wool',
  wildflowers: 'Wildflowers',
  witch: 'Witch',
  wolf: 'Wolf',
  wooden_axe: 'Wooden Axe',
  wooden_hoe: 'Wooden Hoe',
  wooden_pickaxe: 'Wooden Pickaxe',
  wooden_shovel: 'Wooden Shovel',
  yellow_bed: 'Yellow Bed',
  yellow_terracotta: 'Yellow Terracotta',
  zombie: 'Zombie',
  zombie_villager: 'Zombie Villager',
  zombified_piglin: 'Zombified Piglin'
};

/**
 * Get a human-readable display name for a Minecraft item/block/entity ID.
 * Falls back to title-cased snake_case if not found.
 */
export function getItemName(id: string): string {
  const raw = id.replace('minecraft:', '');
  return (
    ITEM_NAMES[raw] ??
    raw
      .split('_')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
  );
}
