/**
 * Runtime translation loader for Minecraft IDs.
 *
 * Load translations.json (generated by scripts/generate-translations.py)
 * before using translateId(). The JSON is a flat { bareId: "Display Name" }
 * dictionary covering items, blocks, entities, stats, and advancements.
 */

let translations: Record<string, string> = {};

export async function loadTranslations(): Promise<void> {
  const res = await fetch(`${import.meta.env.BASE_URL}data/translations.json`);
  translations = await res.json();
}

function titleCase(s: string): string {
  return s
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Translate a Minecraft ID to its in-game display name.
 *
 * Accepts full namespaced IDs (e.g., "minecraft:diamond_sword") or bare IDs
 * (e.g., "diamond_sword"). For advancements, accepts full IDs like
 * "minecraft:story/mine_stone" or bare paths like "story/mine_stone".
 *
 * Recipe advancement IDs (e.g., "minecraft:recipes/building_blocks/stone")
 * are resolved to the item's display name.
 *
 * Falls back to title-casing for unknown IDs (e.g., modded items).
 * Returns the bare ID as a title-cased string if translations aren't loaded yet.
 */
export function translateId(id: string): string {
  const raw = id.replace('minecraft:', '');

  if (raw.includes('/')) {
    if (raw.startsWith('recipes/')) {
      const itemKey = raw.split('/').pop()!;
      return translations[itemKey] ?? titleCase(itemKey);
    }
    return translations[raw] ?? titleCase(raw.split('/').pop()!);
  }

  return translations[raw] ?? titleCase(raw);
}
